steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:     
  - --destination=gcr.io/$PROJECT_ID/form-frontend:latest  
  - --cache=true
  - --cache-ttl=336h
  - --dockerfile=Dockerfile.prod