const code2Province = {
  "1" : "Thành phố Hà Nội",
  "2" : "Tỉnh Hà Giang",
  "4" : "Tỉnh Cao Bằng",
  "6" : "Tỉnh Bắc Kạn",
  "8" : "Tỉnh Tuyên Quang",
  "10" : "Tỉnh Lào Cai",
  "11" : "Tỉnh Điện Biên",
  "12" : "Tỉnh Lai Châu",
  "14" : "Tỉnh Sơn La",
  "15" : "Tỉnh Yên Bái",
  "17" : "Tỉnh Hòa Bình",
  "19" : "Tỉnh Thái Nguyên",
  "20" : "Tỉnh Lạng Sơn",
  "22" : "Tỉnh Quảng Ninh",
  "24" : "Tỉnh Bắc Giang",
  "25" : "Tỉnh Phú Thọ",
  "26" : "Tỉnh Vĩnh Phúc",
  "27" : "Tỉnh Bắc Ninh",
  "30" : "Tỉnh Hải Dương",
  "31" : "Thành phố Hải Phòng",
  "33" : "Tỉnh Hưng Yên",
  "34" : "Tỉnh Thái Bình",
  "35" : "Tỉnh Hà Nam",
  "36" : "Tỉnh Nam Định",
  "37" : "Tỉnh Ninh Bình",
  "38" : "Tỉnh Thanh Hóa",
  "40" : "Tỉnh Nghệ An",
  "42" : "Tỉnh Hà Tĩnh",
  "44" : "Tỉnh Quảng Bình",
  "45" : "Tỉnh Quảng Trị",
  "46" : "Tỉnh Thừa Thiên Huế",
  "48" : "Thành phố Đà Nẵng",
  "49" : "Tỉnh Quảng Nam",
  "51" : "Tỉnh Quảng Ngãi",
  "52" : "Tỉnh Bình Định",
  "54" : "Tỉnh Phú Yên",
  "56" : "Tỉnh Khánh Hòa",
  "58" : "Tỉnh Ninh Thuận",
  "60" : "Tỉnh Bình Thuận",
  "62" : "Tỉnh Kon Tum",
  "64" : "Tỉnh Gia Lai",
  "66" : "Tỉnh Đắk Lắk",
  "67" : "Tỉnh Đắk Nông",
  "68" : "Tỉnh Lâm Đồng",
  "70" : "Tỉnh Bình Phước",
  "72" : "Tỉnh Tây Ninh",
  "74" : "Tỉnh Bình Dương",
  "75" : "Tỉnh Đồng Nai",
  "77" : "Tỉnh Bà Rịa - Vũng Tàu",
  "79" : "Thành phố Hồ Chí Minh",
  "80" : "Tỉnh Long An",
  "82" : "Tỉnh Tiền Giang",
  "83" : "Tỉnh Bến Tre",
  "84" : "Tỉnh Trà Vinh",
  "86" : "Tỉnh Vĩnh Long",
  "87" : "Tỉnh Đồng Tháp",
  "89" : "Tỉnh An Giang",
  "91" : "Tỉnh Kiên Giang",
  "92" : "Thành phố Cần Thơ",
  "93" : "Tỉnh Hậu Giang",
  "94" : "Tỉnh Sóc Trăng",
  "95" : "Tỉnh Bạc Liêu",
  "96" : "Tỉnh Cà Mau"
}

const ethnic_group_type = {
    "Kinh": "01",
    "Tày": "02",
    "Thái": "03",
    "Hoa": "04",
    "Khơ-me": "05",
    "Mường": "06",
    "Nùng": "07",
    "Hmông": "08",
    "Dao": "09",
    "Gia-rai": "10",
    "Ngái": "11",
    "Ê-đê": "12",
    "Ba-na": "13",
    "Xơ-đăng": "14",
    "Sán Chay": "15",
    "Cơ-ho": "16",
    "Chăm": "17",
    "Sán Dìu": "18",
    "Hrê": "19",
    "Mnông": "20",
    "Ra-glai": "21",
    "Xtiêng": "22",
    "Bru-Vân Kiều": "23",
    "Thổ": "24",
    "Giáy": "25",
    "Cơ-tu": "26",
    "Gié-Triêng": "27",
    "Mạ": "28",
    "Khơ-mú": "29",
    "Co": "30",
    "Ta-ôi": "31",
    "Chơ-ro": "32",
    "Kháng": "33",
    "Xinh-mun": "34",
    "Hà Nhì": "35",
    "Chu-ru": "36",
    "Lào": "37",
    "La Chi": "38",
    "La Ha": "39",
    "Phù Lá": "40",
    "La Hủ": "41",
    "Lự": "42",
    "Lô Lô": "43",
    "Chứt": "44",
    "Mảng": "45",
    "Pà Thẻn": "46",
    "Cơ Lao": "47",
    "Cống": "48",
    "Bố Y": "49",
    "Si La": "50",
    "Pu Péo": "51",
    "Brâu": "52",
    "Ơ Đu": "53",
    "Rơ-măm": "54",
    "Ca dong": "55",
    "Nước ngoài": "99"
}

const country_list_type = {
    "Việt Nam": "VN",
    "Afghanistan": "AF",
    "Åland Islands": "AX",
    "Albania": "AL",
    "Algeria": "DZ",
    "American Samoa": "AS",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguilla": "AI",
    "Antarctica": "AQ",
    "Antigua And Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Aruba": "AW",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bermuda": "BM",
    "Bhutan": "BT",
    "Bolivia": "BO",
    "Bosnia And Herzegovina": "BA",
    "Botswana": "BW",
    "Bouvet Island": "BV",
    "Brazil": "BR",
    "British Indian Ocean Territory": "IO",
    "Brunei Darussalam": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Cape Verde": "CV",
    "Cayman Islands": "KY",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Christmas Island": "CX",
    "Cocos (keeling) Islands": "CC",
    "Colombia": "CO",
    "Comoros": "KM",
    "Congo": "CG",
    "Congo, The Democratic Republic Of The": "CD",
    "Cook Islands": "CK",
    "Costa Rica": "CR",
    "Côte D'ivoire": "CI",
    "Croatia": "HR",
    "Cuba": "CU",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Ethiopia": "ET",
    "Falkland Islands (malvinas)": "FK",
    "Faroe Islands": "FO",
    "Fiji": "FJ",
    "Finland": "FI",
    "France": "FR",
    "French Guiana": "GF",
    "French Polynesia": "PF",
    "French Southern Territories": "TF",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Greece": "GR",
    "Greenland": "GL",
    "Grenada": "GD",
    "Guadeloupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guinea": "GN",
    "Guinea-bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Heard Island And Mcdonald Islands": "HM",
    "Holy See (vatican City State)": "VA",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran, Islamic Republic Of": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Israel": "IL",
    "Italy": "IT",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kiribati": "KI",
    "Korea, Democratic People's Republic Of": "KP",
    "Korea, Republic Of": "KR",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Lao People's Democratic Republic": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libyan Arab Jamahiriya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Macao": "MO",
    "Macedonia, The Former Yugoslav Republic Of": "MK",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marshall Islands": "MH",
    "Martinique": "MQ",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mayotte": "YT",
    "Mexico": "MX",
    "Micronesia, Federated States Of": "FM",
    "Moldova, Republic Of": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montserrat": "MS",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Netherlands": "NL",
    "Netherlands Antilles": "AN",
    "New Caledonia": "NC",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "Niue": "NU",
    "Norfolk Island": "NF",
    "Northern Mariana Islands": "MP",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palau": "PW",
    "Palestinian Territory, Occupied": "PS",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Pitcairn": "PN",
    "Poland": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Qatar": "QA",
    "Réunion": "RE",
    "Romania": "RO",
    "Russian Federation": "RU",
    "Rwanda": "RW",
    "Saint Helena": "SH",
    "Saint Kitts And Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Pierre And Miquelon": "PM",
    "Saint Vincent And The Grenadines": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "Sao Tome And Principe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia And Montenegro": "CS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Solomon Islands": "SB",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Georgia And The South Sandwich Islands": "GS",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan": "SD",
    "Suriname": "SR",
    "Svalbard And Jan Mayen": "SJ",
    "Swaziland": "SZ",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syrian Arab Republic": "SY",
    "Taiwan, Province Of China": "TW",
    "Tajikistan": "TJ",
    "Tanzania, United Republic Of": "TZ",
    "Thailand": "TH",
    "Timor-leste": "TL",
    "Togo": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinidad And Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Turks And Caicos Islands": "TC",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States": "US",
    "United States Minor Outlying Islands": "UM",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Vatican City State See Holy See": "VA",
    "Venezuela": "VE",    
    "Virgin Islands, British": "VG",
    "Virgin Islands, U.s.": "VI",
    "Wallis And Futuna": "WF",
    "Western Sahara": "EH",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW"
};


const religons_type = {
    "Không": 5,
    "Thiên chúa giáo": 6,
    "Phật giáo": 7,
    "Hồi giáo": 8,
    "Công giáo": 12,
    "Ấn độ giáo": 13
}
const marital_status_type = {
    "Đã kết hôn": 1,
    "Độc thân": 2,
    "Góa phụ": 4,
    "Ly hôn": 6
}

const education_type = [
  "Cao đẳng", "Đại học", "Trên đại học", "Lao động phổ thông", "Trung cấp chuyên nghiệp", "Dạy nghề chuyên nghiệp", "Khác"
];

const education_field_type= [
    "Ngành Toán tin",
    "Ngành Toán ứng dụng",
    "Ngành Khoa học tính toán",
    "Ngành Toán học",
    "Ngành Thống kê",
    "Ngành Thú y",
    "Ngành Quản lý bệnh viện",
    "Ngành Tổ chức và quản lý y tế",
    "Ngành Y đa khoa",
    "Ngành Điều dưỡng",
    "Ngành Hóa dược",
    "Ngành Dược học",
    "Ngành Y học cổ truyền",
    "Ngành Y học dự phòng",
    "Ngành Y tế công cộng",
    "Ngành Kỹ thuật phục hồi chức năng",
    "Ngành Kỹ thuật hình ảnh y học",
    "Ngành Kỹ thuật xét nghiệm y học",
    "Ngành Kỹ thuật phục hình răng",
    "Ngành Răng - Hàm - Mặt",
    "Ngành Dinh dưỡng",
    "Ngành Hộ sinh",
    "Ngành Công nghệ da giày",
    "Ngành Công nghệ vật liệu dệt, may",
    "Ngành Công nghệ sợi, dệt",
    "Ngành Công nghệ chế biến lâm sản",
    "Ngành Công nghệ dệt, may",
    "Ngành Đảm bảo chất lượng và an toàn thực phẩm",
    "Ngành Công nghệ chế biến thuỷ sản",
    "Ngành Công nghệ sau thu hoạch",
    "Ngành Kỹ thuật thực phẩm",
    "Ngành Công nghệ thực phẩm",
    "Ngành Luật quốc tế",
    "Ngành Luật kinh tế",
    "Ngành Luật",
    "Ngành Lâm sinh",
    "Ngành Quản lý thủy sản",
    "Ngành Khai thác thủy sản",
    "Ngành Bệnh học thủy sản",
    "Ngành Nuôi trồng thủy sản",
    "Ngành Phát triển nông thôn",
    "Ngành Kinh tế nông nghiệp",
    "Ngành Kinh doanh nông nghiệp",
    "Ngành Công nghệ rau hoa quả và cảnh quan",
    "Ngành Bảo vệ thực vật",
    "Ngành Khoa học cây trồng",
    "Ngành Nông học",
    "Ngành Chăn nuôi",
    "Ngành Khoa học đất",
    "Ngành Khuyến nông",
    "Ngành Nông nghiệp",
    "Ngành Lâm học",
    "Ngành Quản lý tài nguyên rừng",
    "Ngành Lâm nghiệp đô thị",
    "Ngành Ngôn ngữ Khmer",
    "Ngành Hán Nôm",
    "Ngành Tiếng Việt và văn hoá Việt Nam",
    "Ngành Văn hoá các dân tộc thiểu số Việt Nam",
    "Ngành Sáng tác Văn học",
    "Ngành Ngôn ngữ Ả Rập",
    "Ngành Ngôn ngữ Hàn Quốc",
    "Ngành Ngôn ngữ Nhật",
    "Ngành Ngôn ngữ Bồ Đào Nha",
    "Ngành Ngôn ngữ Tây Ban Nha",
    "Ngành Ngôn ngữ Trung Quốc",
    "Ngành Ngôn ngữ Đức",
    "Ngành Ngôn ngữ Pháp",
    "Ngành Ngôn ngữ Nga",
    "Ngành Ngôn ngữ Anh",
    "Ngành Quản lý văn hóa",
    "Ngành Văn hóa học",
    "Ngành Văn học",
    "Ngành Ngôn ngữ học",
    "Ngành Lịch sử",
    "Ngành Tôn giáo học",
    "Ngành Chủ nghĩa xã hội khoa học",
    "Ngành Triết học",
    "Ngành Bảo hộ lao động",
    "Ngành Quản lý đất đai",
    "Ngành Kinh tế tài nguyên thiên nhiên",
    "Ngành Quản lý tài nguyên và môi trường",
    "Ngành Kỹ thuật máy tính",
    "Ngành Kỹ thuật phần mềm",
    "Ngành Mạng máy tính và truyền thông dữ liệu",
    "Ngành Khoa học máy tính",
    "Ngành An toàn thông tin",
    "Ngành Công nghệ thông tin",
    "Ngành Kỹ thuật tuyển khoáng",
    "Ngành Kỹ thuật dầu khí",
    "Ngành Kỹ thuật mỏ",
    "Ngành Kỹ thuật địa vật lý",
    "Ngành Kỹ thuật trắc địa - bản đồ",
    "Ngành Kỹ thuật địa chất",
    "Ngành Kỹ thuật hạt nhân",
    "Ngành Vật lý kỹ thuật",
    "Ngành Kỹ thuật môi trường",
    "Ngành Kỹ thuật vật liệu kim loại",
    "Ngành Kỹ thuật vật liệu",
    "Ngành Kỹ thuật hoá học",
    "Ngành Kỹ thuật điều khiển và tự động hóa",
    "Ngành Kỹ thuật y sinh",
    "Ngành Kỹ thuật điện tử - viễn thông",
    "Ngành Kỹ thuật điện",
    "Ngành Kỹ thuật không gian",
    "Ngành Kỹ thuật hàng không",
    "Ngành Kỹ thuật hệ thống công nghiệp",
    "Ngành Kỹ thuật công nghiệp",
    "Ngành Kỹ thuật cơ khí động lực",
    "Ngành Cơ kỹ thuật",
    "Ngành Kinh tế đối ngoại",
    "Ngành Kinh tế",
    "Ngành Hệ thống thông tin",
    "Ngành Kiểm toán",
    "Ngành Bảo hiểm",
    "Ngành Kinh doanh thương mại",
    "Ngành Khoa học quản lý",
    "Ngành Hệ thống thông tin quản lý",
    "Ngành Quản lý dự án",
    "Ngành Quan hệ lao động",
    "Ngành Quản lý công",
    "Ngành Quản trị nhân lực",
    "Ngành Quản trị văn phòng",
    "Ngành Kế toán",
    "Ngành Tài chính - Ngân hàng",
    "Ngành Kinh doanh quốc tế",
    "Ngành Marketing",
    "Ngành Bất động sản",
    "Ngành Thương mại điện tử",
    "Ngành Quản trị kinh doanh",
    "Ngành Kỹ thuật xây dựng",
    "Ngành Quản lý xây dựng",
    "Ngành Kinh tế xây dựng",
    "Ngành Quy hoạch vùng và đô thị",
    "Ngành Đô thị học",
    "Ngành Kỹ thuật cấp thoát nước",
    "Ngành Kỹ thuật tài nguyên nước",
    "Ngành Địa kỹ thuật xây dựng",
    "Ngành Kỹ thuật cơ sở hạ tầng",
    "Ngành Kỹ thuật xây dựng công trình giao thông",
    "Ngành Kỹ thuật xây dựng công trình biển",
    "Ngành Kỹ thuật xây dựng công trình thủy",
    "Ngành Thiết kế nội thất",
    "Ngành Kiến trúc cảnh quan",
    "Ngành Kiến trúc",
    "Ngành Đông Nam Á học",
    "Ngành Quốc tế học",
    "Ngành Toán kinh tế",
    "Ngành Thống kê Kinh tế",
    "Ngành Kinh tế Chính trị",
    "Ngành Nhân học",
    "Ngành Xã hội học",
    "Ngành Tâm lý học giáo dục",
    "Ngành Tâm lý học",
    "Ngành Kinh tế quốc tế",
    "Ngành Kinh tế phát triển",
    "Ngành Kinh tế đầu tư",
    "Ngành Hàn Quốc học",
    "Ngành Nhật Bản học",
    "Ngành Việt Nam học",
    "Ngành Đông phương học",
    "Ngành Xây dựng Đảng và chính quyền nhà nước",
    "Ngành Quan hệ quốc tế",
    "Ngành Quản lý nhà nước",
    "Ngành Chính trị học",
    "Ngành Địa lý học",
    "Ngành Khoa học vật liệu",
    "Ngành Hóa học",
    "Ngành Cơ học",
    "Ngành Vật lý nguyên tử và hạt nhân",
    "Ngành Vật lý học",
    "Ngành Thiên văn học",
    "Ngành Hải dương học",
    "Ngành Thủy văn học",
    "Ngành Khí tượng và khí hậu học",
    "Ngành Địa lý tự nhiên",
    "Ngành Địa chất học",
    "Ngành Bản đồ học",
    "Ngành Khoa học môi trường",
    "Ngành Kỹ thuật sinh học",
    "Ngành Sinh học ứng dụng",
    "Ngành Công nghệ sinh học",
    "Ngành Sinh học",
    "Ngành Quản lý thể dục thể thao",
    "Ngành Quản trị nhà hàng và dịch vụ ăn uống",
    "Ngành Quản trị khách sạn",
    "Ngành Kinh tế gia đình",
    "Ngành Y sinh học thể dục thể thao",
    "Ngành Quản trị dịch vụ du lịch và lữ hành",
    "Ngành Du lịch",
    "Ngành Công tác thanh thiếu niên",
    "Ngành Công tác xã hội",
    "Ngành Khoa học hàng hải",
    "Ngành Kinh tế vận tải",
    "Ngành Quản lý hoạt động bay",
    "Ngành Khai thác vận tải",
    "Ngành Robot và Trí tuệ nhân tạo",
    "Ngành Công nghệ kỹ thuật điện, điện tử",
    "Ngành Kỹ thuật in",
    "Ngành Công nghệ kỹ thuật ô tô",
    "Ngành Kỹ thuật tàu thuỷ",
    "Ngành Kỹ thuật nhiệt",
    "Ngành Kỹ thuật cơ điện tử",
    "Ngành Kỹ thuật cơ khí",
    "Ngành Công nghê kỹ thuật vật liệu xây dựng",
    "Ngành Công nghệ kỹ thuật công trình xây dựng",
    "Ngành Công nghệ kỹ thuật giao thông",
    "Ngành Công nghệ kỹ thuật kiến trúc",
    "Ngành Bảo dưỡng công nghiệp",
    "Ngành Công nghệ chế tạo máy",
    "Ngành Quản lý công nghiệp",
    "Ngành Kinh tế công nghiệp",
    "Ngành Logistics và Quản lý chuỗi cung ứng",
    "Ngành Kinh doanh xuất bản phẩm",
    "Ngành Xuất bản",
    "Ngành Bảo tàng học",
    "Ngành Lưu trữ học",
    "Ngành Quản lý thông tin",
    "Ngành Thông tin - thư viện",
    "Ngành Quan hệ công chúng",
    "Ngành Truyền thông quốc tế",
    "Ngành Công nghệ truyền thông",
    "Ngành Truyền thông đại chúng",
    "Ngành Truyền thông đa phương tiện",
    "Ngành Báo chí",
    "Ngành Quân sự cơ sở",
    "Ngành Phòng cháy chữa cháy và cứu nạn cứu hộ",
    "Ngành Quản lý nhà nước về an ninh trật tự",
    "Ngành Trinh sát cảnh sát",
    "Ngành Kỹ thuật hình sự",
    "Ngành Biên phòng",
    "Ngành Hậu cần quân sự",
    "Ngành Điều tra hình sự",
    "Ngành Trinh sát an ninh",
    "Ngành Diễn viên kịch, điện ảnh - truyền hình",
    "Ngành Diễn viên sân khấu kịch hát",
    "Ngành Công nghệ điện ảnh, truyền hình",
    "Ngành Biên kịch sân khấu",
    "Ngành Thanh nhạc",
    "Ngành Chỉ huy âm nhạc",
    "Ngành Sáng tác âm nhạc",
    "Ngành Mỹ thuật đô thị",
    "Ngành Âm nhạc học",
    "Ngành Gốm",
    "Ngành Thiết kế công nghiệp",
    "Ngành Quay phim",
    "Ngành Hội họa",
    "Ngành Biên đạo múa",
    "Ngành Thiết kế mỹ thuật sân khấu, điện ảnh",
    "Ngành Thiết kế thời trang",
    "Ngành Thiết kế đồ họa",
    "Ngành Diễn viên múa",
    "Ngành Thiết kế âm thanh, ánh sáng",
    "Ngành Nhiếp ảnh",
    "Ngành Biểu diễn nhạc cụ truyền thống",
    "Ngành Huấn luyện múa",
    "Ngành Điêu khắc",
    "Ngành Đạo diễn sân khấu",
    "Ngành Biên kịch điện ảnh, truyền hình",
    "Ngành Đạo diễn Điện ảnh - Truyền hình",
    "Ngành Lý luận, lịch sử và phê bình sân khấu",
    "Ngành Piano",
    "Ngành Biểu diễn nhạc cụ phương Tây",
    "Ngành Sư phạm Khoa học tự nhiên",
    "Ngành Quản lý giáo dục",
    "Ngành Giáo dục đặc biệt",
    "Ngành Giáo dục Thể chất",
    "Ngành Giáo dục Chính trị",
    "Ngành Giáo dục Công dân",
    "Ngành Giáo dục Tiểu học",
    "Ngành Giáo dục Mầm non",
    "Ngành Giáo dục Quốc phòng - An ninh",
    "Ngành Huấn luyện thể thao",
    "Ngành Sư phạm Công nghệ",
    "Ngành Sư phạm Tiếng Hàn Quốc",
    "Ngành Sư phạm Tiếng Nhật",
    "Ngành Sư phạm Tiếng Trung Quốc",
    "Ngành Sư phạm Tiếng Pháp",
    "Ngành Sư phạm Tiếng Anh",
    "Ngành Sư phạm Mỹ thuật",
    "Ngành Sư phạm Âm nhạc",
    "Ngành Sư phạm Tiếng Nga",
    "Ngành Sư phạm Địa lý",
    "Ngành Sư phạm Lịch sử",
    "Ngành Sư phạm Ngữ văn",
    "Ngành Sư phạm Kỹ thuật nông nghiệp",
    "Ngành Sư phạm Kỹ thuật công nghiệp",
    "Ngành Sư phạm Sinh học",
    "Ngành Sư phạm Hóa học",
    "Ngành Sư phạm Vật lý",
    "Ngành Sư phạm Tin học",
    "Ngành Sư phạm Toán học",
    "Khác"
]

const position_type = [
  "Công nhân", "Phó Giám đốc", "Giám đốc", "Trưởng nhóm", "Nhân viên", "Trợ lý Tổng Giám đốc", "Giám đốc sản xuất", "Trợ lý kho", "Trợ lý sản xuất", "Ca trưởng", "Cán bộ chuyên trách","Khác"
]

module.exports = { 
  code2Province,
  country_list_type,
  ethnic_group_type,
  religons_type,
  marital_status_type,
  education_type, education_field_type,position_type
}